### ISSUE TITLE
Error: Undefined rule plugin/no-unused-selectors

### ISSUE THREAD

**Issue by Goldziher** [nodaguti/stylelint-no-unused-selectors#113]
I have the following setup:

In my package.json:
```
                "stylelint": "^10.1.0",
         	"stylelint-config-prettier": "^5.2.0",
		"stylelint-config-recess-order": "^2.0.3",
		"stylelint-config-recommended-scss": "^3.3.0",
		"stylelint-config-standard": "^18.3.0",
		"stylelint-no-unused-selectors": "^1.0.8",
		"stylelint-prettier": "^1.1.1",
		"stylelint-scss": "^3.9.1",
```

And this is my stylelint.config.js

```
module.exports = {
	extends: [
		'stylelint-config-recommended-scss',
		'stylelint-config-recess-order',
		'stylelint-prettier/recommended',
	],
	rules: {
		'no-empty-source': null,
		'plugin/no-unused-selectors': true,
	},
}
```

Node modules are installed correctly. Nonetheless I am getting this error when I try to run stylelint:
```
Error: Undefined rule plugin/no-unused-selectors
    at module.exports (/Users/naamanhirschfeld/workspace/polyrepo/yoda/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at Object.keys.forEach.ruleName (/Users/naamanhirschfeld/workspace/polyrepo/yoda/node_modules/stylelint/lib/augmentConfig.js:325:13)
    at Array.forEach (<anonymous>)
    at normalizeAllRuleSettings (/Users/naamanhirschfeld/workspace/polyrepo/yoda/node_modules/stylelint/lib/augmentConfig.js:318:29)
    at augmentConfigBasic.then.then.then.augmentedConfig (/Users/naamanhirschfeld/workspace/polyrepo/yoda/node_modules/stylelint/lib/augmentConfig.js:94:14)
```

**Comment by nodaguti** [comment]
Hello,

You need to register the plugin by putting

```
"plugins": [
  "stylelint-no-unused-selectors"
],
```

to your stylelint.config.js (See https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#plugins for more details).

I'm sorry for the fact that this is not documented in the README. I'll update it.

Thank you!

**Comment by nodaguti** [comment]
This issue should be fixed now so I'm closing. Feel free to reopen if you find it to keep reproducing.
